// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQolR30_M1yvu77dvTS2F2qnN9vVW3BQs',
    appId: '1:963903160741:web:568553cea045e5e2db284c',
    messagingSenderId: '963903160741',
    projectId: 'sanskrt-web-app',
    authDomain: 'sanskrt-web-app.firebaseapp.com',
    databaseURL: 'https://sanskrt-web-app-default-rtdb.firebaseio.com',
    storageBucket: 'sanskrt-web-app.appspot.com',
    measurementId: 'G-S579LLJ3C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTMweSpii3e2bEbKyT6NDV-4h4fCN9d4',
    appId: '1:963903160741:android:c95603087666c382db284c',
    messagingSenderId: '963903160741',
    projectId: 'sanskrt-web-app',
    databaseURL: 'https://sanskrt-web-app-default-rtdb.firebaseio.com',
    storageBucket: 'sanskrt-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_WacSVyitTHD2SNh-F6s683VrrLcmuw',
    appId: '1:963903160741:ios:8ad0fb0f1ffabe9fdb284c',
    messagingSenderId: '963903160741',
    projectId: 'sanskrt-web-app',
    databaseURL: 'https://sanskrt-web-app-default-rtdb.firebaseio.com',
    storageBucket: 'sanskrt-web-app.appspot.com',
    iosBundleId: 'com.example.sanskritWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_WacSVyitTHD2SNh-F6s683VrrLcmuw',
    appId: '1:963903160741:ios:c9ddd5d08b5a3319db284c',
    messagingSenderId: '963903160741',
    projectId: 'sanskrt-web-app',
    databaseURL: 'https://sanskrt-web-app-default-rtdb.firebaseio.com',
    storageBucket: 'sanskrt-web-app.appspot.com',
    iosBundleId: 'com.example.sanskritWebApp.RunnerTests',
  );
}
